name: Bug Report
description: Report a bug or issue
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide details to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? Provide a clear description of the bug.
      placeholder: CLI throws error when parsing schema file with optional fields
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Create schema file with optional field: `{"fields": {"name": {"type": "string", "optional": true}}}`
        2. Run command: `ordis extract --schema test.schema.json --input test.txt`
        3. Observe error message
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
      placeholder: CLI should parse the schema successfully and proceed with extraction
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: CLI exits with error "Invalid schema format" without processing optional field
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your system configuration
      placeholder: |
        - OS: macOS 14.0
        - Node.js: 18.17.0
        - ordis-cli: 0.1.0
        - LLM provider: Ollama (llama3.1:8b)
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low (minor inconvenience)
        - Medium (affects functionality)
        - High (blocks important work)
        - Critical (complete failure)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs (Optional)
      description: Any relevant error messages or logs
      placeholder: Paste error output here (use --debug for verbose output)